fx_version 'bodacious'

game 'gta5'

description 'ESXPHONE'
version '1.2 FIX 5'

ui_page 'html/index.html'

shared_script '@es_extended/imports.lua'

files {
	'html/index.html', 
	'html/css/app.css', 
	'html/css/vendor.css', 
	'html/sjs/build.js', 
	'html/js/buildv.js', 
	'html/js/client.js', 
	'html/js/config.js', 
	'html/js/server.js', 
	'html/static/config/config.json',
	'html/static/img/fingerprint.png',
	'html/static/img/2048/blackjack.png',
	'html/static/img/2048/cards.png',
	'html/static/img/2048/logo.png',
	'html/static/img/2048/logo2.png',
	'html/static/img/2048/snake.png',
	'html/static/img/2048/arrow/down.png',
	'html/static/img/2048/arrow/left.png',
	'html/static/img/2048/arrow/right.png',
	'html/static/img/2048/arrow/up.png',
	'html/static/img/background/back001.jpg',
	'html/static/img/background/back002.jpg',
	'html/static/img/background/back003.jpg',
	'html/static/img/background/color.jpg',
	'html/static/img/background/humo.jpg',
	'html/static/img/background/iluminacion.jpg',
	'html/static/img/background/neon.jpg',
	'html/static/img/background/newphone.png',
	'html/static/img/background/oscuridad.jpg',
	'html/static/img/background/paisajes.jpg',
	'html/static/img/background/playa.jpg',
	'html/static/img/background/sahesiz.png',
	'html/static/img/background/tokio.jpg',
	'html/static/img/camera/camera.png',
	'html/static/img/camera/crosss.png',
	'html/static/img/camera/tick.png',
	'html/static/img/icons/9gag.png',
	'html/static/img/icons/appstore.png',
	'html/static/img/icons/calculator.png',
	'html/static/img/icons/call.png',
	'html/static/img/icons/camera.png',
	'html/static/img/icons/carsales.png',
	'html/static/img/icons/contacts.png',
	'html/static/img/icons/games.png',
	'html/static/img/icons/gotur.png',
	'html/static/img/icons/gps.png',
	'html/static/img/icons/haber.png',
	'html/static/img/icons/instagram.png',
	'html/static/img/icons/instagram2.png',
	'html/static/img/icons/jobm.png',
	'html/static/img/icons/logo.png',
	'html/static/img/icons/mail.png',
	'html/static/img/icons/maps.png',
	'html/static/img/icons/market.png',
	'html/static/img/icons/messages.png',
	'html/static/img/icons/music2.png',
	'html/static/img/icons/news.png',
	'html/static/img/icons/notes.png',	
	'html/static/img/icons/photo.png',
	'html/static/img/icons/photos.png',
	'html/static/img/icons/race.png',
	'html/static/img/icons/raceing.png',
	'html/static/img/icons/record.png',
	'html/static/img/icons/reddit.png',
	'html/static/img/icons/settings.png',
	'html/static/img/icons/sms.png',
	'html/static/img/icons/splashtchat.png',
	'html/static/img/icons/stocks.png',
	'html/static/img/icons/switch_camera.png',
	'html/static/img/icons/taxijob.png',
	'html/static/img/icons/tchat.png',
	'html/static/img/icons/tinder.png',
	'html/static/img/icons/tinder2.png',
	'html/static/img/icons/tinderlogo2.png',
	'html/static/img/icons/twitter.png',
	'html/static/img/icons/vale.png',
	'html/static/img/icons/valeuser.png',
	'html/static/img/icons/wallet.png',
	'html/static/img/icons/yellow.png',
	'html/static/img/icons/youtubeicon.png',
	'html/static/img/jobs/ambulance.png',
	'html/static/img/jobs/police.png',
	'html/static/img/newtheme/pngegg.png',
	'html/static/img/newtheme/taxi.jpg',
	'html/static/img/newtheme/taxi.png',
	'html/static/img/newtheme/taxi2.png',
	'html/static/img/newtheme/lock/Background-01089A0E-6777-4711-814D-F1BB5611D5BE.png',
	'html/static/img/newtheme/lock/Background-28E0F607-CF42-4778-A21B-31E09B26D6B3.png',
	'html/static/img/newtheme/lock/Background-E032FE0A-6B1F-4D34-B4BD-066021685CB5.png',
	'html/static/img/newtheme/lock/Camera-Icon-4BC816BC-8511-48B0-895E-D40D44A25DF0.png',
	'html/static/img/newtheme/lock/Home-Indicator-0F5F8286-EA1B-4984-838E-818F03041977.png',
	'html/static/img/newtheme/lock/Icon-B5F27F20-B5C5-4B63-9790-3D517733BD9D.png',	
	'html/static/img/newtheme/lock/lockedicon.png',
	'html/static/img/tinder/like-txt.png',
	'html/static/img/tinder/like.png',
	'html/static/img/tinder/nope-txt.png',
	'html/static/img/tinder/nope.png',
	'html/static/img/tinder/super-like.png',
	'html/static/img/tinder/super-txt.png',
	'html/static/img/twitter/banner.jpg',
	'html/static/img/twitter/bird.png',
	'html/static/img/twitter/default_profile.png',
	'html/static/sound/bella_ciao.ogg',
	'html/static/sound/camera.ogg',
	'html/static/sound/InstagramSound.ogg',
	'html/static/sound/iphone_11.ogg',
	'html/static/sound/jobnotifsound.ogg',
	'html/static/sound/Phone_Call_Sound_Effect.ogg',
	'html/static/sound/ring.ogg',
	'html/static/sound/tchatNotification-viejo.ogg',
	'html/static/sound/Twitter_Sound_Effect-viejo.ogg',
	'html/static/sound/xtentacion.ogg',
	'html/static/sound/Yellow_Sound_Effect.ogg',
}

client_script {
	"@es_extended/locale.lua",
	"locales/en.lua",
	"config.lua",
	'html/js/client.js',
	"client/animation.lua",
	"client/client.lua",
	"client/photo.lua",
	"client/app_tchat.lua",
	"client/bank.lua",
	"client/twitter.lua",
	"client/yellow.lua",
	"client/fatura.lua",
	"client/instagram.lua",
	"client/valet.lua",
	"client/client2.lua",
	"client/youtube.lua"
}

server_script {
	"@mysql-async/lib/MySQL.lua",
	"@es_extended/locale.lua",
	"locales/en.lua",
	"config.lua",
	'html/js/config.js',
	'html/js/server.js',
	"server/server.lua",
	"server/app_tchat.lua",
	"server/twitter.lua",
    "server/yellow.lua",
	"server/bank.lua",
	"server/fatura.lua",
	"server/instagram.lua",
	"server/valet.lua",
	"server/server2.lua"
}
